language: cpp

addons:
  apt:
    packages:
      - libpcap-dev

matrix:
  include:
    - name: "jammy/amd64/gcc"
      os: linux
      compiler: gcc
      dist: jammy
      arch: amd64
    - name: "jammy/arm64/gcc"
      os: linux
      compiler: gcc
      dist: jammy
      arch: arm64
    
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
