name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: install deps
       run: sudo apt install libpcap-dev libnl-3-200 libnl-nf-3-dev libmnl0 libmnl-dev libssl1.1 libssl-dev libncurses6 libncurses-dev check
     - name: cmake
       run: cmake -S . -B build -G "Unix Makefiles"
     - name: build
       run: cmake --build build
     - name: test
       run: ctest --test-dir build
  
